# services
#   - metrics.prod
#   - metrics.test
#   - logs.prod
#   - logs.test
#   - backups.prod
#   - backups.test
#   - app.prod
#   - app.test

services:
  consul-server-eu-dc:
    image: consul:1.15.4
    ports:
      - "8500:8500"
      - "8600:8600"
      # - "8301"
    entrypoint: consul
    volumes:
      - ./consul-home/consul-server-eu-dc:/consul-home
    healthcheck: &server_healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: [
      "agent", 
        "-server", 
        "-ui", 
        "-node", "server-eu-dc",
        "--datacenter", "eu-dc",
        "-bootstrap-expect", "1", 
        "-client", "0.0.0.0", 
        "--data-dir", "/consul-home"
      ]
    networks:
      vpc_consul:
        ipv4_address: 10.10.0.5

  consul-server-eu-dc2:
    depends_on: &server_main_deps
      consul-server-eu-dc:
        condition: service_healthy
    image: consul:1.15.4
    entrypoint: consul
    ports:
      - "8501:8500"
    volumes:
      - ./consul-home/consul-server-eu-dc2:/consul-home
    healthcheck: *server_healthcheck
    command: [
      "agent", 
        "-server", 
        "-ui", 
        "-node", "server-eu-dc2",
        "--datacenter", "eu-dc2",
        "-bootstrap-expect", "1", 
        "-client", "0.0.0.0", 
        "--data-dir", "/consul-home",
        "--retry-join-wan", "10.10.0.5"
      ]
    networks:
      vpc_consul:
        ipv4_address: 10.10.0.6

  consul-server-us-dc:
    depends_on: *server_main_deps
    image: consul:1.15.4
    entrypoint: consul
    ports:
      - "8502:8500"
    volumes:
      - ./consul-home/consul-server-us-dc:/consul-home
    healthcheck: *server_healthcheck
    command: [
      "agent", 
        "-server", 
        "-ui", 
        "-node", "server-us-dc",
        "--datacenter", "us-dc",
        "-bootstrap-expect", "1", 
        "-client", "0.0.0.0", 
        "--data-dir", "/consul-home",
        "--retry-join-wan", "10.10.0.5"
      ]
    networks:
      vpc_consul:
        ipv4_address: 10.10.0.7

  consul-server-asia-dc:
    depends_on: *server_main_deps
    image: consul:1.15.4
    entrypoint: consul
    ports:
      - "8503:8500"
    volumes:
      - ./consul-home/consul-server-asia-dc:/consul-home
    healthcheck: *server_healthcheck
    command: [
      "agent", 
        "-server", 
        "-ui", 
        "-node", "server-asia-dc",
        "--datacenter", "asia-dc",
        "-bootstrap-expect", "1",
        "-client", "0.0.0.0",
        "--data-dir", "/consul-home",
        "--retry-join-wan", "10.10.0.5"
      ]
    networks:
      vpc_consul:
        ipv4_address: 10.10.0.8


## EU-DC1
  node-01-eu-dc-metrics.prod:
    depends_on: &agent_deps
      consul-server-eu-dc:
        condition: service_healthy        
      consul-server-eu-dc2:
        condition: service_healthy
      consul-server-us-dc:
        condition: service_healthy
      consul-server-asia-dc:
        condition: service_healthy
    build: &consul_svc_image_build
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./consul-home/node-01.eu-dc.metrics.prod:/consul-home
    environment:
      - DATA_CENTER=eu-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-01.eu-dc.metrics.prod
      - RETRY_JOIN_IP=10.10.0.5
      - NODE_ENV=metrics
      - NODE_STAGE=prod
    networks:
      vpc_consul:
        ipv4_address: 10.10.10.1
  node-02-eu-dc-metrics.prod:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-02.eu-dc.metrics.prod:/consul-home
    environment:
      - DATA_CENTER=eu-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-02.eu-dc.metrics.prod
      - RETRY_JOIN_IP=10.10.0.5
      - NODE_ENV=metrics
      - NODE_STAGE=prod
    networks:
      vpc_consul:
        ipv4_address: 10.10.10.2
  node-01-eu-dc-metrics.test:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-01.eu-dc.metrics.test:/consul-home
    environment:
      - DATA_CENTER=eu-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-01.eu-dc.metrics.test
      - RETRY_JOIN_IP=10.10.0.5
      - NODE_ENV=metrics
      - NODE_STAGE=test
    networks:
      vpc_consul:
        ipv4_address: 10.10.10.3
  node-01-eu-dc-logs.test:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-01.eu-dc.logs.test:/consul-home
    environment:
      - DATA_CENTER=eu-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-01.eu-dc.logs.test
      - RETRY_JOIN_IP=10.10.0.5
      - NODE_ENV=logs
      - NODE_STAGE=test
    networks:
      vpc_consul:
        ipv4_address: 10.10.10.4
  node-01-eu-dc-logs.prod:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-01.eu-dc.logs.prod:/consul-home
    environment:
      - DATA_CENTER=eu-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-01.eu-dc.logs.prod
      - RETRY_JOIN_IP=10.10.0.5
      - NODE_ENV=logs
      - NODE_STAGE=prod
    networks:
      vpc_consul:
        ipv4_address: 10.10.10.5
  node-02-eu-dc-logs.prod:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-02.eu-dc.logs.prod:/consul-home
    environment:
      - DATA_CENTER=eu-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-02.eu-dc.logs.prod
      - RETRY_JOIN_IP=10.10.0.5
      - NODE_ENV=logs
      - NODE_STAGE=prod
    networks:
      vpc_consul:
        ipv4_address: 10.10.10.6
  # EU-DC2
  node-03-eu-dc2-logs.prod:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-03.eu-dc2.logs.prod:/consul-home
    environment:
      - DATA_CENTER=eu-dc2
      - DATA_DIR=/consul/home
      - NODE_NAME=node-03.eu-dc2.logs.prod
      - RETRY_JOIN_IP=10.10.0.5,10.10.0.6,10.10.0.7,10.10.0.8
      - NODE_ENV=logs
      - NODE_STAGE=prod
    networks:
      vpc_consul:
        ipv4_address: 10.10.20.1
  node-01-eu-dc2-backups.prod:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-01.eu-dc2.backups.prod:/consul-home
    environment:
      - DATA_CENTER=eu-dc2
      - DATA_DIR=/consul/home
      - NODE_NAME=node-01.eu-dc2.backups.prod
      - RETRY_JOIN_IP=10.10.0.5,10.10.0.6,10.10.0.7,10.10.0.8
      - NODE_ENV=backups
      - NODE_STAGE=prod
    networks:
      vpc_consul:
        ipv4_address: 10.10.20.2
  node-02-eu-dc2-backups.prod:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-02.eu-dc2.backups.prod:/consul-home
    environment:
      - DATA_CENTER=eu-dc2
      - DATA_DIR=/consul/home
      - NODE_NAME=node-02.eu-dc2.backups.prod
      - RETRY_JOIN_IP=10.10.0.5,10.10.0.6,10.10.0.7,10.10.0.8
      - NODE_ENV=backups
      - NODE_STAGE=prod
    networks:
      vpc_consul:
        ipv4_address: 10.10.20.3
  # US-DC
  node-01-us-dc1-backups.test:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-01.us-dc.backups.prod:/consul-home
    environment:
      - DATA_CENTER=us-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-01.us-dc.backups.prod
      - RETRY_JOIN_IP=10.10.0.5,10.10.0.6,10.10.0.7,10.10.0.8
      - NODE_ENV=backups
      - NODE_STAGE=test
    networks:
      vpc_consul:
        ipv4_address: 10.10.30.1
  node-02-us-dc1-backups.test:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-02.us-dc.backups.test:/consul-home
    environment:
      - DATA_CENTER=us-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-02.us-dc.backups.test
      - RETRY_JOIN_IP=10.10.0.5,10.10.0.6,10.10.0.7,10.10.0.8
      - NODE_ENV=backups
      - NODE_STAGE=test
    networks:
      vpc_consul:
        ipv4_address: 10.10.30.2
  node-01-us-dc1-app.prod:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-01.us-dc.app.prod:/consul-home
    environment:
      - DATA_CENTER=us-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-01.us-dc.app.prod
      - RETRY_JOIN_IP=10.10.0.5,10.10.0.6,10.10.0.7,10.10.0.8
      - NODE_ENV=app
      - NODE_STAGE=prod
    networks:
      vpc_consul:
        ipv4_address: 10.10.30.3
  # ASIA-DC
  node-01-asia-dc1-app.test:
    depends_on: *agent_deps
    build: *consul_svc_image_build
    volumes:
      - ./consul-home/node-01.asia-dc.app.test:/consul-home
    environment:
      - DATA_CENTER=asia-dc
      - DATA_DIR=/consul/home
      - NODE_NAME=node-01.asia-dc.app.test
      - RETRY_JOIN_IP=10.10.0.5,10.10.0.6,10.10.0.7,10.10.0.8
      - NODE_ENV=app
      - NODE_STAGE=test
    networks:
      vpc_consul:
        ipv4_address: 10.10.40.1

networks:
  vpc_consul:
    ipam:
      config:
        - subnet: 10.10.0.0/16